### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by mrpnectar** [deedy/mac_computer_use#1]
Receiving this error when attempting to run streamlit.py:

(venv) ➜  mac_computer_use git:(main) ✗ streamlit run streamlit.py
Traceback (most recent call last):
  File "/Users/john/mac_computer_use/venv/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/Users/john/mac_computer_use/streamlit.py", line 22, in <module>
    from streamlit.delta_generator import DeltaGenerator
ModuleNotFoundError: No module named 'streamlit.delta_generator'; 'streamlit' is not a package

**Comment by Sayedardhi** [comment]
uninstalling and reinstalling streamlit might for you. what worked for me was trying:

conda update -c conda-forge streamlit -y

**Comment by benthecoder** [comment]
@mrpnectar rename the streamlit.py file to something else, like app.py
